### ISSUE TITLE
How to download stacked bar chart from Cibersortx?

### ISSUE THREAD

**Issue by bharati-mehani** [ysuzukilab/Cibersortx#2]
Hi 
Is there any way with which I can download the stacked bar chart from Cibersortx?

Thanks

**Comment by nina2727** [comment]
Hi biobug16,

I'm afraid you probably can't directly save the stacked bar chart from Cibersotx's interface.
You could try one of the following workaround:
1. Take a screenshot of the bar plot from Cibersotx's website
2. Download the output matrix in xlsx/csv/txt format and use Microsoft excel etc. to easily make your own chart
3. Try out our code Cibersortx/Sort_Cibersortx_output_fractions.ipynb (disclaimer: the comments are in JPN)

Hope this helps
