### ISSUE TITLE
unable run CIBERSORTx

### ISSUE THREAD

**Issue by Yichel518** [ysuzukilab/Cibersortx#3]
Hello great team,

I am your old user of CIBERSORT. As far as I'm concerned, this great tool experience is awesome. This time I want to try your new tool about CIBERSORTx to get the expression and marker of cell types identified from tissue. Although I login in your website but can not start for running. Is it because the tools are not open yet ? What should I do next?

Best wish!

Yichel

**Comment by nina2727** [comment]
Hi Yichel,

Unfortunately, we are not the developers of Cibersort/Cibersortx.
Like you, we are also users benefiting significantly thanks to the awesome Cibersort team!
Please try contacting them directly:
https://cibersortx.stanford.edu/contact.php

As a side note, I myself am able to use Cibersortx... Hope you'll soon be able to enjoy it too!

**Comment by Yichel518** [comment]
Thank you for your reply. 
By the way, can you use the  website of CIBERSORTx ? Could you please share the method with me?
thank you!

**Comment by Yichel518** [comment]
![image](https://user-images.githubusercontent.com/52185244/100187351-e4dcc800-2f22-11eb-8499-2a79c32d130b.png)
I can not login in the website and there is no menu to run CIBERSORTx.

**Comment by nina2727** [comment]
Did you register? Note that you need a different account than for Cibersort.

**Comment by Yichel518** [comment]
I managed to register with two accounts, but I just couldn't log in. I don't know why

**Comment by nina2727** [comment]
Are you sure your account has already been activated?
Or did you register today?

I personally received two emails after registering for Cibersortx.
One titled 'CIBERSORTx Registration Confirmation', the other titled 'Approved: CIBERSORTx Account Activation Request'.
If you haven't received them, I would advice you to wait for a day or two for the Cibersortx to come around (took a day in my case), then try emailing them.
