### ISSUE TITLE
Why is Cibersortx not showing any of my log or job results with an error: "The system queue is not running"

### ISSUE THREAD

**Issue by bharati-mehani** [ysuzukilab/Cibersortx#4]
Hi Admin and [nina2727](https://github.com/nina2727),
I have been using Cibersortx since past few days but suddenly it has stopped showing the log and the processed results for any of my jobs and throwing a warning: "The system queue is not running.  Please contact the CIBERSORTx Team at cibersortx@gmail.com."

I have contacted their team but haven't heard anything back from them. Do any of you have any idea how can I resolve this issue?

Thanks

**Comment by nina2727** [comment]
Hi biobug16,

Unfortunately I've never encountered the same problem and have no insight to share.
Maybe try deleting some runs results/data?

Hope the Cibersortx Team has come back to you.
