### ISSUE TITLE
How to increase the analysis speed for a large data matrix?

### ISSUE THREAD

**Issue by bharati-mehani** [ysuzukilab/Cibersortx#5]
Hi @nina2727 , 
I have a data matrix having 20000 genes from 450 samples. 
I am new with Cibersortx and have few queries. These may be naive questions:
1) In order to increase the speed for the analysis, is it ok if I divide my samples into two or more smaller groups (like 225 each) and later merge them together.
2) Is there a way with which I can increase the number of threads? (by default it uses 3 threads)

Looking forward to your answers.
Thanks

**Comment by nina2727** [comment]
1. Yes, that would be the workaround I'd use if I were you.
2. If the Cibersort platform allows youth increase the number of threads, that might help.
