### ISSUE TITLE
Cybersortx's error: ../lib/cx.sh: line 7: 10746 Killed

### ISSUE THREAD

**Issue by bharati-mehani** [ysuzukilab/Cibersortx#6]
Hi @nina2727,

I am trying to run Cibersortx but every time I get a similar error:
`../lib/cx.sh: line 7: 10746 Killed                  Rscript $1
or 
../lib/cx.sh: line 7: 22543 Killed                  Rscript $1

`
Is it (10746) a random number or there is some issue with the gene at 10746 row. Can anyone please help, what does this error mean?
I am really stuck. Kindly help. 

Thanks

**Comment by nina2727** [comment]
I'd suggest manually checking your file at gene 10746.
