### ISSUE TITLE
Are the deconvolved gene expression values (already in fraction) from Cibersotx normalized or require any further normalization like TMM?

### ISSUE THREAD

**Issue by bharati-mehani** [ysuzukilab/Cibersortx#7]
Hi all, i am using Cibersotx to deconvolve TCGA gene expression data and getting my the expression values in fractions. I am not sure whether these should be considered as normalized count to perform differential expression among samples or we require any normalization as TMM in EdgeR. Anybody has any experience with this? 
Thanks in advance.

@nina2727 would you like to make any suggestion here?

**Comment by nina2727** [comment]
The result of Cibersortx should be the proportion of each cell type per cell in fractions.
