### ISSUE TITLE
Error in mcfork, Cannot allocate memory 

### ISSUE THREAD

**Issue by quanc1989** [ysuzukilab/Cibersortx#8]
Hi, 
Recently, Errors always happen (Impute Cell Fractions) as follows, I don’t know how to fix it.

Errors were encountered in CIBERSORTx configuration, run aborted:

Error in mcfork() : 
  unable to fork, possible reason: Cannot allocate memory
Calls: CIBERSORTxFractions -> CoreAlg -> mclapply -> lapply -> FUN -> mcfork
Execution halted
Warning message:
system call failed: Cannot allocate memory 

Job Parameters used for this run:

Date: 2021-02-01 08:00:23
Job type: Impute Cell Fractions
Signature matrix file: CIBERSORTx_Job3_signatures.brain.roc.seurat4.res14.majortype_inferred_phenoclasses.CIBERSORTx_Job3_signatures.brain.roc.seurat4.res14.majortype_inferred_refsample.bm.K999.txt
Mixture file: mixture.brain.roc.majortype.txt
Batch correction: disabled
Disable quantile normalization: true
Run mode (relative or absolute): relative
Permutations: 1

Quan Cheng

**Comment by nina2727** [comment]
Please contact the Cibersort team (https://cibersortx.stanford.edu/contact.php) for issues with the tool, thank you.
